# Análise de dados com Python

Buscar no repositório "study_pandas" mais informações sobre análises estatísticas usando python. 

**Principais processos para análises assertivas:** 

        - 1) Importar base de dados 
        - 2) Visualizar base de dados (Observar quais são as colunas/ quantas linhas há em cada uma)
        - 3) Tratamento de dados  **
        - 4) Análise inicial 
        - 5) Insights

#### **Desafio**

Suspeita de 26% de desistência de clientes com uma empresa. Como solucionar isso, uma vez que isso indica perda de valores?

In [1]:
import pandas as pd

In [2]:
#Importação de dados e visualização da base de dados
frame = pd.read_csv(r'data\telecom_users.csv')
display(frame)

,Unnamed: 0,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,1869,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,4528,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.2,Nao,NaN
2,6344,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6739,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.5,Nao,NaN
4,432,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.5,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,3772,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95,Sim,NaN
5982,5191,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.3,Nao,NaN
5983,5226,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,5390,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,860,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.3,Nao,NaN

### **Tratamento de dados**

a) Informações inúteis devem ser retiradas. 
        
        colunas com valores vazios; 
        informações que não acrescentam em nada;

b) Valores reconhecidas de maneiras erradas. 

        Verificar se como o python esta reconhecendo os tipos de dado em cada coluna. 

c) Tratar os NaN.

In [3]:
# a) Deleção de linhas e de colunas de uma tabela 
# axis = 0 --> linha
# axis = 1 --> coluna 

frame = frame.drop(frame.columns[0], axis=1)

In [4]:
# b) Non-Null --> informa a quantidade de linhas preenchidas em cada coluna 
# Dtype: object similar a string

frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5986 non-null   object
 1   Genero                  5986 non-null   object
 2   Aposentado              5986 non-null   int64
 3   Casado                  5986 non-null   object
 4   Dependentes             5985 non-null   object
 5   MesesComoCliente        5986 non-null   int64
 6   ServicoTelefone         5986 non-null   object
 7   MultiplasLinhas         5986 non-null   object
 8   ServicoInternet         5986 non-null   object
 9   ServicoSegurancaOnline  5986 non-null   object
 10  ServicoBackupOnline     5986 non-null   object
 11  ProtecaoEquipamento     5986 non-null   object
 12  ServicoSuporteTecnico   5986 non-null   object
 13  ServicoStreamingTV      5986 non-null   object
 14  ServicoFilmes           5986 non-null   object
 15  TipoContrato            5986 non-null   object
 16  FaturaDigital           5986 non-null   object
 17  FormaPagamento          5986 non-null   object
 18  ValorMensal             5986 non-null   float64
 19  TotalGasto              5986 non-null   object
 20  Churn                   5985 non-null   object
 21  Codigo                  0 non-null      float64
dtypes: float64(2), int64(2), object(18)
memory usage: 1.0+ MB

In [5]:
#Tranformar valores 'object' para númericos

frame['TotalGasto'] = pd.to_numeric(frame['TotalGasto'], errors = 'coerce')

#Parâmetro coerce é extremamente importante, uma vez que, se tiver um erro de digitação (entradas que não são números), 
#o código acrescenta 'NaN'.

display(frame.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5986 entries, 0 to 5985
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IDCliente               5986 non-null   object
 1   Genero                  5986 non-null   object
 2   Aposentado              5986 non-null   int64
 3   Casado                  5986 non-null   object
 4   Dependentes             5985 non-null   object
 5   MesesComoCliente        5986 non-null   int64
 6   ServicoTelefone         5986 non-null   object
 7   MultiplasLinhas         5986 non-null   object
 8   ServicoInternet         5986 non-null   object
 9   ServicoSegurancaOnline  5986 non-null   object
 10  ServicoBackupOnline     5986 non-null   object
 11  ProtecaoEquipamento     5986 non-null   object
 12  ServicoSuporteTecnico   5986 non-null   object
 13  ServicoStreamingTV      5986 non-null   object
 14  ServicoFilmes           5986 non-null   object
 15  TipoContrato            5986 non-null   object
 16  FaturaDigital           5986 non-null   object
 17  FormaPagamento          5986 non-null   object
 18  ValorMensal             5986 non-null   float64
 19  TotalGasto              5976 non-null   float64
 20  Churn                   5985 non-null   object
 21  Codigo                  0 non-null      float64
dtypes: float64(3), int64(2), object(17)
memory usage: 1.0+ MB

None

In [6]:
#c) Tratamento de valores vazios

#all = Deletar somente linhas/colunas cujos valores são vazios 
#any = Deletar linhas/colunas com pelo menos 1 valor vazio 

frame.dropna(how='all',axis=1)
frame.dropna(how='any', axis=0)

display(frame)

,IDCliente,Genero,Aposentado,Casado,Dependentes,MesesComoCliente,ServicoTelefone,MultiplasLinhas,ServicoInternet,ServicoSegurancaOnline,...,ServicoSuporteTecnico,ServicoStreamingTV,ServicoFilmes,TipoContrato,FaturaDigital,FormaPagamento,ValorMensal,TotalGasto,Churn,Codigo
0,7010-BRBUU,Masculino,0,Sim,Sim,72,Sim,Sim,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,2 anos,Nao,CartaoCredito,24.10,1734.65,Nao,NaN
1,9688-YGXVR,Feminino,0,Nao,Nao,44,Sim,Nao,Fibra,Nao,...,Nao,Sim,Nao,Mensal,Sim,CartaoCredito,88.15,3973.20,Nao,NaN
2,9286-DOJGF,Feminino,1,Sim,Nao,38,Sim,Sim,Fibra,Nao,...,Nao,Nao,Nao,Mensal,Sim,DebitoAutomatico,74.95,2869.85,Sim,NaN
3,6994-KERXL,Masculino,0,Nao,Nao,4,Sim,Nao,DSL,Nao,...,Nao,Nao,Sim,Mensal,Sim,BoletoEletronico,55.90,238.50,Nao,NaN
4,2181-UAESM,Masculino,0,Nao,Nao,2,Sim,Nao,DSL,Sim,...,Nao,Nao,Nao,Mensal,Nao,BoletoEletronico,53.45,119.50,Nao,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5981,0684-AOSIH,Masculino,0,Sim,Nao,1,Sim,Nao,Fibra,Sim,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,95.00,95.00,Sim,NaN
5982,5982-PSMKW,Feminino,0,Sim,Sim,23,Sim,Sim,DSL,Sim,...,Sim,Sim,Sim,2 anos,Sim,CartaoCredito,91.10,2198.30,Nao,NaN
5983,8044-BGWPI,Masculino,0,Sim,Sim,12,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Mensal,Sim,BoletoEletronico,21.15,306.05,Nao,NaN
5984,7450-NWRTR,Masculino,1,Nao,Nao,12,Sim,Sim,Fibra,Nao,...,Nao,Sim,Sim,Mensal,Sim,BoletoEletronico,99.45,1200.15,Sim,NaN
5985,4795-UXVCJ,Masculino,0,Nao,Nao,26,Sim,Nao,Nao,SemInternet,...,SemInternet,SemInternet,SemInternet,Anual,Nao,CartaoCredito,19.80,457.30,Nao,NaN

In [7]:
#Quantificar quantas pessoas desistiram 

display(frame['Churn'].value_counts())
display(frame['Churn'].value_counts(normalize=True))

Nao    4398
Sim    1587
Name: Churn, dtype: int64

Nao    0.734837
Sim    0.265163
Name: Churn, dtype: float64